# Generated by Django 2.0.2 on 2018-01-01 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdownFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_files/', verbose_name='Uploaded file')),
                ('slug', models.CharField(max_length=36, verbose_name='Secret URL Part')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Password')),
                ('max_downloads', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum downloads')),
                ('download_counter', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Download counter')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Expiration date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
