# Generated by Django 2.0.2 on 2018-02-08 17:53

import django.core.validators
from django.db import migrations, models
import updown.models


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updownfile',
            name='file',
            field=models.FileField(upload_to='uploaded_files/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='updownfile',
            name='max_downloads',
            field=updown.models.RealPositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum downloads'),
        ),
    ]
