# Generated by Django 2.0.2 on 2018-02-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updownfile',
            name='name',
        ),
    ]
