# Generated by Django 2.0.2 on 2018-02-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0004_auto_20180202_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updownfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
    ]
