# Generated by Django 2.0.2 on 2018-02-05 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0007_auto_20180202_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updownfile',
            name='expires_at',
            field=models.DateField(verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='updownfile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='updownfile',
            name='password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Password'),
        ),
    ]
