# Generated by Django 2.0.2 on 2018-02-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0010_auto_20180206_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='updownfile',
            name='download_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Download counter'),
            preserve_default=False,
        ),
    ]
