# Generated by Django 2.0.2 on 2018-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0011_updownfile_download_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updownfile',
            name='download_counter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Download counter'),
        ),
    ]
