# Generated by Django 2.0.2 on 2018-02-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0012_auto_20180206_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updownfile',
            name='download_counter',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Download counter'),
        ),
    ]
