# Generated by Django 2.0.2 on 2018-02-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdownFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='File name')),
                ('file', models.FileField(upload_to='', verbose_name='Uploaded file')),
                ('url_part', models.CharField(max_length=9, verbose_name='Secret URL Part')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('expiration_date', models.DateTimeField(verbose_name='Expiration date')),
            ],
        ),
    ]
