# Generated by Django 2.0.2 on 2018-02-02 09:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_remove_updownfile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updownfile',
            old_name='expiration_date',
            new_name='expire_at',
        ),
        migrations.AddField(
            model_name='updownfile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 9, 5, 51, 242026, tzinfo=utc), verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updownfile',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
