# Generated by Django 2.0.2 on 2018-02-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180202_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updownfile',
            old_name='url_part',
            new_name='slug',
        ),
    ]
