# Generated by Django 2.0.2 on 2018-02-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180202_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updownfile',
            old_name='expire_at',
            new_name='expires_at',
        ),
    ]
