# Generated by Django 2.0.2 on 2018-02-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180205_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='updownfile',
            name='max_downloads',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum download Count'),
        ),
    ]
